### ISSUE TITLE
lamp files not loading in order; module not found

### ISSUE THREAD

**Issue by wrburgess** [crismali/magic_lamp#13]
So we had Mocha + Teaspoon + MagicLamp working smooth on **CodeShip**, but our monolithic `magic_lamp.rb` file was getting a bit out of hand.

Tests are passing fine on CodeShip, here:

![codeship_cruising](https://cloud.githubusercontent.com/assets/69637/6535249/2b763444-c409-11e4-842f-cd807063157c.jpg)

We broke up the single file into several using the MagicLamp docs:

![codeship_cruising_2](https://cloud.githubusercontent.com/assets/69637/6535279/61a24706-c409-11e4-8f38-1191966c3abd.jpg)

Locally, tests passed without a problem:

![1__bash](https://cloud.githubusercontent.com/assets/69637/6535313/a0ab380e-c409-11e4-815d-b7fa673c05de.png)

But CodeShip hit an iceberg:

![codeship_sinks_1](https://cloud.githubusercontent.com/assets/69637/6535318/b141186e-c409-11e4-8fcd-0b569a3c265a.jpg)

![codeship_sinks_2](https://cloud.githubusercontent.com/assets/69637/6535323/b873179a-c409-11e4-99f8-61b74ee404bc.jpg)

Any thoughts on why the CodeShip environment would have trouble loading separate MagicLamp files while localhost is smooth sailing?

**Comment by crismali** [comment]
@wrburgess What version are you using?

If you're on 1.5, try adding `rake mll` to your test task before running teaspoon. That might give us a better clue.

**Comment by wrburgess** [comment]
`gem "magic_lamp", "1.5.0"`

I'll try to run the `rake mll` on codeship...passes fine on local

**Comment by crismali** [comment]
Just to explain my reasoning, I'm interested in how that fails on Codeship since Teaspoon tends to hide errors.

**Comment by wrburgess** [comment]
totally get it...i just have to grab a few minutes to put the problem back in after I reverted it...

rb

**Comment by wrburgess** [comment]
So it's a loading order error, I believe.

I only extracted one file, `tutor_assignments_controller_lamp.rb`, from the `magic_lamp.rb` file and this is where it bombed on CodeShip.

`AuthenticatedUser` is a module in the `magic_lamp.rb` file

Not sure of the remedy, as these files were ordered alphabetically on localhost and it worked fine. 

Also, I underscored the module file on localhost to prevent loading errors, and it worked. Loading behavior on CodeShip is different, I guess.

```
Linting Magic Lamp configuration...
Configuration looks good!
Linting lamp files...
The following files are broken:

File: /home/rof/src/github.com/innovationsforlearning/centralstation/spec/javascripts/fixtures/tutor_assignment_controller_lamp.rb
Error: NameError: uninitialized constant AuthenticatedUser
/home/rof/src/github.com/innovationsforlearning/centralstation/spec/javascripts/fixtures/tutor_assignment_controller_lamp.rb:1:in `<top (required)>'
```

**Comment by crismali** [comment]
I think moving the `AuthenticatedUser` module to the `magic_lamp_config.rb` file might take care of this. I think locally you're getting a different file load order than on Codeship. Moving helper modules to the config file will make sure they're loaded before any lamp files are loaded.

**Comment by wrburgess** [comment]
So that works, but I guess the next question is:

Is the config file the best place to put MagicLamp-specific modules?

**Comment by crismali** [comment]
It's the only place where it will be loaded by default, but you could also load the files in yourself in the config file. Although you probably just want to be able to give magic lamp a directory or list of files to load every time it generates fixtures...

**Comment by wrburgess** [comment]
Thanks for the help. The Lamp is working pretty well for our app!
