### ISSUE TITLE
Loading helper modules

### ISSUE THREAD

**Issue by crismali** [crismali/magic_lamp#14]
Should probably document that helper modules should be loaded in the config file. Could also add a support path option that would load a given directory or list of files or something before loading fixtures. It could also be included as part of the lint process too. This would help prevent issues like #13 before they even happen.

**Comment by wrburgess** [comment]
maybe `lamp_helper.rb`, in the same spirit as `spec/spec_helper.rb` and `spec/rails_helper.rb`?

**Comment by crismali** [comment]
I added [a note to the readme about this](https://github.com/crismali/magic_lamp#loading-helpers) with an example. I think that'll do the trick for now, if there's more of a need to have this built into the gem we can always reopen this.
