### ISSUE TITLE
Repackage gems without giant log files

### ISSUE THREAD

**Issue by BlakeMesdag** [crismali/magic_lamp#15]
The gems that are currently distributed on rubygems.org have enormous log files included:

```
vagrant@vagrant:~/.gem/ruby/2.1.5/gems/magic_lamp-1.5.0$ du -hs *
124K	app
8.0K	config
60K	lib
12K	LICENSE
20K	README.md
122M	spec
```

The worst offender is `spec/dummy/log/test.log` which rings in at 96M. @crismali can you repackage the 1.5.0 gem (not sure about the others) with a `git clean -df`prior to packaging them?

**Comment by BlakeMesdag** [comment]
1.5.1 seems to include logs as well, although not as huge:

```
vagrant@vagrant:~/.gem/ruby/2.1.5/gems/magic_lamp-1.5.1$ du -hs spec/dummy/log/*
800K	spec/dummy/log/development.log
2.2M	spec/dummy/log/test.log
```

**Comment by crismali** [comment]
Thanks for bringing this up, the [1.5.2 release](https://github.com/crismali/magic_lamp/releases/tag/v1.5.2) resolves this.
