### ISSUE TITLE
Missing something trivial :)

### ISSUE THREAD

**Issue by rstudner** [crismali/magic_lamp#20]
So I have a page with the following setup:

/dashboard/index.html.erb

that file, of course, loads some partials
/dashboard/_widget1.html.erb
/dashboard/_widget2.html.erb

so if I do:
```
MagicLamp.register_fixture do
  @organizations = [Organization.new(id: 1, name: 'foo')]
  render "dashboard/index"
end
```

Then do MagicLamp.load('dashboard/index') it will crash, because it has no idea what _widget1 etc is.

```
Error: ActionView::Template::Error: Missing partial application/_widget1 with {:locale=>[:en], :formats=>[:html, :text, :js, :css, :ics, :csv, :vcf, :png, :jpeg, :gif, :bmp, :tiff, :mpeg, :xml, :rss, :atom, :yaml, :multipart_form, :url_encoded_form, :json, :pdf, :zip], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :arb, :jbuilder]}.
```
What's the trick? (which i'm guessing is obvious, and possibly even in the docs but I missed it).

Thanks!

**Comment by rstudner** [comment]
Ahh.  all my part loads were not fully relatively path'd.

i.e. I had
```
<%= render 'widget1' %>
instead of
<%= render 'dashboard/widget1' %>
```

Interestingly this has always worked, but magic lamp really dislikes the missing relative path.

Is that configurable somehow or did I Just have bad syntax to begin with?

**Comment by crismali** [comment]
@rstudner, by default Magic Lamp will render the template using `ApplicationController` which generally requires full paths to partials. Errors like this can generally be avoided by specifying the controller like so:

```ruby
MagicLamp.register_fixture(controller: DashboardController) do
  @organizations = [Organization.new(id: 1, name: 'foo')]
  render "dashboard/index"
end
```

With the controller specified you also don't need to qualify the path when calling `render` (ie `render "dashboard/index"` can just be `render :index`).

Let me know if specifying the controller takes care of this for you.

**Comment by rstudner** [comment]
Brilliant!  thank you so much.

I'm a long time java/scala developer who also does UI (ember, angular, knockout, whatever).. and thus my RAILS experience is low and some of these rather obvious (I assume to rails people) things throw me for a loop :)

Appreciate the help!
