### ISSUE TITLE
Sprockets caches `all_fixtures`

### ISSUE THREAD

**Issue by crismali** [crismali/magic_lamp#21]
This forces the user to have to blow away `tmp` every time they change a fixture. Need to find a way to either configure or otherwise hook into sprockets to prevent this caching for Magic Lamp.

**Comment by kris-luminar** [comment]
I'm interested in this as I may have encountered this problem without realizing it. The issue I experienced was that changes to a JavaScript file in `app/assets/javascripts` wouldn't get picked up when I ran Teaspoon. Is this the same issue or something different?

**Comment by crismali** [comment]
@kris-luminar this issue is about how if you're using Sprockets to require your Magic Lamp templates and then change a fixture in a `_lamp.rb` file the fixture doesn't update even if you bounce the server. You'd have to blow away the Sprockets cache in `tmp`. It sounds like there's an issue (configuration or bug) with Teaspoon/Sprockets the way you've described it.

**Comment by crismali** [comment]
could come in handy https://github.com/rails/sprockets#the-depend_on-directive

**Comment by crismali** [comment]
`ActionDispatch::Reloader.to_cleanup` may help as well

**Comment by crismali** [comment]
Added a note about how to prevent sprockets caching into the readme
