### ISSUE TITLE
Magic Lamp and RAILS_ENV=test

### ISSUE THREAD

**Issue by rstudner** [crismali/magic_lamp#25]
I didn’t see this in the docs.

So — everything works perfectly… except! (has to be one of those right?)

if I do RAILS_ENV=test before running teaspoon , or do RAILS_ENV=test rake magic_lamp:lint I get:

Error: ActionView::Template::Error: called `redirect_to` while creating a fixture, this is probably not what you want to have happen.

Is magic lamp “intended” to run with a test rails_env, or only development?

**Comment by crismali** [comment]
@rstudner It's not intended for any environment in particular. I've even seen people set up a "javascript_test" environment to prevent development data from interfering with fixture data when saving records to the database for use in fixtures. 

That being said, it looks like you must be calling a controller method that calls `redirect_to` conditionally (based on the environment) in one of your fixtures.

**Comment by rstudner** [comment]
I realized after the fact (talking to the more Rails knowledgable folks).  Our development environment, if you weren't logged int, would just make you "user #1"

Thus, RAILS_ENV=test, all the Pundit policies were saying: "hey, you aren't logged in" and redirecting (magic lamp's attempt to render the page) to the login page haha.

So trying to do the magic_lamp_config type setup to actually create/login a user.

**Comment by rstudner** [comment]
We implemented the authstub stuff, so now:
RAILS_ENV=test rake magic_lamp:lint

That totally passes & works.

But trying to run teaspoon, tons of the tests fail still (hrmph).

Trying now to print out the fixture dom's that are being rendered (or not) since of course with no output/visibility its hard to see what is going on hah.

**Comment by crismali** [comment]
I've seen people do things like this to get around some can can pain:

```ruby
fixture do
  def self.can?(*args); true; end
  render :edit
end
```

Teaspoon might have some issues as a result of how it mounts its engine in your application. I know I've personally had issues with Teaspoon + Devise + Better Errors.

**Comment by rstudner** [comment]
All working 100% on our dev boxes, in either environment :)

But -- of course -- it is failing on our jenkins build machine haha (no sure why yet).  One piece at a time! 

Thanks for all your help!
