### ISSUE TITLE
Probably a simple thing I can't figure out

### ISSUE THREAD

**Issue by rstudner** [crismali/magic_lamp#27]
if I have something like:

```ruby
MagicLamp.register_fixture(controller:ShoppingController, extend: AuthStub) do
  render :show
end
```

How do I specify different things for format json, vs html vs pdf etc?

**Comment by crismali** [comment]
@rstudner Do you mean you have templates like this?

```
app/views/foos/show.html
app/views/foos/show.json
app/views/foos/show.pdf
```

If that's the case you can simply call

```ruby
MagicLamp.fixture(controller: FoosController) do
  render "show.html" # or "show.json" or "show.pdf"
end
```

If you want JSON or just any arbitrary string, you can do any of the following:

```ruby
MagicLamp.fixture(controller: FoosController) do
  render json: { something_to: "render as json" }
end

MagicLamp.fixture(controller: FoosController) do
  { something_to: "render as json" }.to_json
end

MagicLamp.fixture(controller: FoosController) do
  some_object.to_xml
end
```

**Comment by rstudner** [comment]
No, I have only a show.html.erb.
the format.json and format.pdf are to service totally difference requests to the same show controller method.  (since so much of the data is the same).

so I can't do, say, "show.json" since I don't a show.json view template etc.

**Comment by crismali** [comment]
If your controller is doing something [like this](http://api.rubyonrails.org/classes/ActionController/MimeResponds.html#method-i-respond_to), you likely won't be able to recycle whichever method calls `respond_to` in your Magic Lamp fixture without more effort than it would take to just build the data structure and call `to_json` or `to_xml` on it

**Comment by rstudner** [comment]
Yeah, the controller is definitely doing a respond_to do |format| etc.
What's odd to me, is that the controller has been doing this for .html and .json for a very long time, with no problems, but now that we've added a format.pdf it all goes crazy haha.

The controller method, basically, is like this:

```
  def show
    respond_to do |format|
      format.html {
        @thingId = params[:id]
      }
      format.pdf do
        @thingId = params[:id]
        actualThing = service.getThing(@thingId)
        @presentableThing = InvestigationsPresenter.new(investigation).as_json
        render pdf: "Thing ##{@thingId}", layout: 'pdf.html'
      end
      format.json do
        actualThing = service.getThing(@thingId)
        render json: ThingPresenter.new(thing)
      end
    end
  end
```

**Comment by rstudner** [comment]
And, just for knowledge sake, the thing that makes it crazy, is in the show.html.erb, there is this line:

        <li><a href="<%= thing_path(thingId, format: :pdf) %>">Export to PDF</a></li>

I remove that, and the linter is happy/tests pass heh.

**Comment by crismali** [comment]
Awesome :)

**Comment by jcquarto** [comment]
wait! how is that 'awesome'? The fellow had to change working code in order to make the magic_lamp test pass.    doesn't that suggest that magic_lamp is somehow not working consistently with Rails' url_helper (which produces the xxxx_path() helper method) ?

**Comment by crismali** [comment]
@jcquarto I think getting things working is always good, but I agree that the workaround/solution is not ideal. Looking over this issue again, I think there are a few things that need to be ruled out before assuming that the path helper methods are broken. 

- We have to make sure the fixture actually sets `@thingId` like the controller does
- We have to know that `thingId` is assigned to the correct value if it's a local variable. If it's a method we have to make sure that it's returning something that isn't `nil`.

Based on the error though (`Error: ActionView::Template::Error: No route matches {:action=>"show", :controller=>"things", :format=>:pdf, :id=>nil}`), it looks like `nil` is ultimately being passed to the path helper.
