### ISSUE TITLE
Inline javascript - method does not exists

### ISSUE THREAD

**Issue by malissa** [crismali/magic_lamp#28]
I'm loading a fixture with a layout that yields a content block :scripts at the bottom. The :scripts content block contains some inline javascript that I set in a partial - something like this:

```ruby
<% content_for :scripts do %>
<script>
    var goTo = function(path){
        window.location.href = path;
    }

    $('body').on('click', function(){
        goTo("/");
    });
</script>
<% end %>
```

This works great in my app but when I run my tests the goTo function does not exist, however, the functions in application.js are all there. How can I fix this?

**Comment by crismali** [comment]
You could `render :foo, layout: true` to render the layout with that particular template. You might also be able to pull the the `script` tag into a partial and load both, ie `MagicLamp.load("foos/show", "layouts/script")`.

But, I'd recommend that you avoid using the `content_for` script blocks and instead use something like [Rails JSKit](https://github.com/daytonn/rails_jskit) so you can keep all of your JavaScript in your `application.js`.

**Comment by crismali** [comment]
Let me know if that helps.

**Comment by malissa** [comment]
I do load the layout with the template and in the inspector I can see the javascript but when I call those functions they are not defined.  What's weird is all of the functions in application.js are defined.

**Comment by malissa** [comment]
Ah I see that application.js is being included by the actual test runner page. So it seems that I can only load html in a fixture.

**Comment by crismali** [comment]
It might be worth it to just stub your `goTo` function since its execution will likely disrupt your tests anyway (it certainly would if you're using Teaspoon as your test runner).

**Comment by crismali** [comment]
@malissa is MagicLamp still giving you any trouble?

**Comment by malissa** [comment]
I just refactored my javascript to get around it :) thanks!
