### ISSUE TITLE
Rendering Layouts?

### ISSUE THREAD

**Issue by eliotc1986** [crismali/magic_lamp#35]
```ruby
MagicLamp.register_fixture(name: "homepage", controller: HomeController) do
  render template: "home/index"
end
```

Is only rendering the `<% yield %>` section of the template, how do we get it to render the entire layout?

**Comment by crismali** [comment]
@eliotc1986 to render the entire layout you need to add a `layout` option to your call to `render`.

```ruby
MagicLamp.register_fixture(name: "homepage", controller: HomeController) do
  render template: "home/index", layout: "application"
end
```

MagicLamp sets the `layout` option to `false` by default because layouts generally contain markup you probably don't want in your JavaScript specs (`script` tags, another `body` tag, etc).

**Comment by eliotc1986** [comment]
@crismali Thanks for the quick response!

This method doesn't seem to be working. 

When I use the following markup:

MagicLamp.register_fixture(name: "homepage", controller: HomeController) do
  render template: "home/index", layout: "home"
end

our layout for the home controller is in the file home.html file.

Is there a way to set the {layout} option to {true} somewhere in the MagicLamp settings?

**Comment by crismali** [comment]
@eliotc1986 when you say it doesn't render the template, do you mean that it's only rendering the layout, rendering nothing, or that it raises an error?

I was able to get a template rendering with the layout in the MagicLamp test suite by adjusting the fixture at the top of [`a_lamp_file_with_a_different_name_lamp.rb`](https://github.com/crismali/magic_lamp/blob/master/spec/dummy/spec/magical/a_lamp_file_with_a_different_name_lamp.rb#L1-L3) like so:

```ruby
MagicLamp.register_fixture(name: "custom_name") do
  render template: "orders/foo", layout: "application"
end
```

Without doing some seriously weird metaprogramming there isn't a way to globally set the `layout` option to `true`.

**Comment by eliotc1986** [comment]
@crismali Thank you for the additional input. Running `<rake magic_lamp:lint>` revealed that I was running into undefined errors from some variables in my layouts. That was causing my layout and template to fail when both were defined in the foo_lamp.rb file.

your method for including layouts is correct. I think adding this to the documentation would be really helpful for other users.

**Comment by crismali** [comment]
13f7c614b15342a854881245fb781838cb437cd2 added documentation for this.

**Comment by eliotc1986** [comment]
Thank you @crismali I appreciate the help!
