### ISSUE TITLE
Unexpected token throw from all_fixtures.js

### ISSUE THREAD

**Issue by rstudner** [crismali/magic_lamp#38]
<img width="313" alt="screen shot 2016-05-09 at 1 49 26 pm" src="https://cloud.githubusercontent.com/assets/209970/15122386/eda9f25e-15ec-11e6-8325-437f0cf222bc.png">

**Comment by crismali** [comment]
If you run `rake mll` to lint your fixtures, you likely have an error. The JS shouldn't have token error there though.

**Comment by crismali** [comment]
This [release](https://github.com/crismali/magic_lamp/releases/tag/v1.8.1) should take care of it.
