### ISSUE TITLE
Asset precompilation in engine.rb

### ISSUE THREAD

**Issue by TheMallen** [crismali/magic_lamp#39]
Getting errors with `MagicLamp` when trying to navigate to `/magic_lamp` due to asset precompilation not being set up. It should probably be set up in `engine.rb` of `MagicLamp` itself instead of client projects. I can submit a PR if you like?

**Comment by crismali** [comment]
@TheMallen which MagicLamp and Rails versions are you using?

PRs are always welcome :)

**Comment by crismali** [comment]
Closing until more information is available.
