### ISSUE TITLE
Error with all_fixtures.js

### ISSUE THREAD

**Issue by molfar** [crismali/magic_lamp#42]
This line

`<% json = MagicLamp.generate_all_fixtures.to_json rescue nil %>`

Always returns nil. So there is no opportunity to load all_fixtures json.

**Comment by crismali** [comment]
@molfar do you get any errors when your run `rake magic_lamp:lint`?

**Comment by molfar** [comment]
No, I was debugging gem code to figure out why all_fixtures does not include any json code in javascript file.

**Comment by crismali** [comment]
It's strange that `rake magic_lamp:lint` isn't catching the error.

If you call `MagicLamp.generate_all_fixtures.to_json` in a `rails console` do you get any errors? If so, do you get any errors when you just call `MagicLamp.generate_all_fixtures` in the console? Also, is there any lint output when you visit your local server at `/magic_lamp/lint`?

It's not possible for `MagicLamp.generate_all_fixtures` to return `nil` itself, so there must be an error somewhere that's causing you to get the result of the `rescue`.

**Comment by crismali** [comment]
Closing until more information can be provided.
